### ISSUE TITLE
Should we import Bootstrap into our application?

### ISSUE THREAD

**Issue by clay-town** [osu-cascades/neap#6]
It would allow for us to build a very mobile-friendly and clean user interface. 
It would also allow for us to easily maintain a consistent style throughout our application. 
What do you think about this, team?

**Comment by ybakos** [comment]
Note that the Rails app boilerplate you are starting with already incorporates bootstrap 4.

**Comment by clay-town** [comment]
Ha! I didn't notice that. Thank you.
