### ISSUE TITLE
Main Landing Page with NIEAP Information

### ISSUE THREAD

**Issue by Amber-K** [osu-cascades/neap#7]
Make a nice page users can go to when they first load the website. Include information about NIEAP. Create this from the starter sign in page and repurpose that page as the homepage.

**Comment by MWidlerSchool** [comment]
Transfer assignment of this issue to self.

**Comment by MWidlerSchool** [comment]
Broadly done, and set as landing page for Nieap. Will break down various improvements as their own issues.
