### ISSUE TITLE
EnergyApplication: verify necessity of redundant (?) fields

### ISSUE THREAD

**Issue by ybakos** [osu-cascades/neap#81]
Users have email addresses, so is it necessary for the EnergyApplication to have an email field?

Same for:

- first_name
- last_name

And the EA model has an address, so why is there also a mailing address? What is the difference? Do we need both?

**Comment by ybakos** [comment]
@MWidlerSchool Some questions:
- a User has a first name and last name, and users are always associated with an EnergyApplication. So do we need to have a separate first name / last name field here in the EnergyApplication table?

Same goes for email. (?)

**Comment by WireHallMedic** [comment]
Redundant reply for documentation clarity, as this was discussed on Discord.

Yes, the user and the applicant should be separate, as these are often different people. The most common example is an adult child filling out the form for an elderly parent.
