### ISSUE TITLE
Schema: energy_applications table, change improper text types to string

### ISSUE THREAD

**Issue by ybakos** [osu-cascades/neap#83]
The text datatype should be reserved for long-form text, like the body of a book. Many of the fields in energy_applications are using the text datatype instead of string.

Discuss, and change them to string where appropriate.

**Comment by ybakos** [comment]
@MWidlerSchool Was using `text` datatypes for fields in the energy_applications table intentional?

**Comment by WireHallMedic** [comment]
Yong is correct, all fields currently listed as text should be strings.

**Comment by WireHallMedic** [comment]
I feel like the proper way to correct this is to add a new migration correcting the existing field types, rather than correcting the existing migrations and requiring db:migrate:reset. Is this correct?

**Comment by ybakos** [comment]
@WireHallMedic That's right - once a migration is shared, you should not go back and change it.

I'll create the migration to fix the schema. 👍
