### ISSUE TITLE
EnergyApplicationsHelper: move `counties` to EnergyApplication::COUNTIES

### ISSUE THREAD

**Issue by ybakos** [osu-cascades/neap#86]
Move this out of the helper layer and into the model.
Replace usage of `counties` with `EnergyApplication::COUNTIES`.

**Comment by ybakos** [comment]
@WireHallMedic This is a quick change but is 15 days old. Do you need me to get it done?

**Comment by MWidlerSchool** [comment]
I believe this is resolved, but new applicants are skipping straight to the energy application. Will mark as complete once I can confirm.
