### ISSUE TITLE
User Landing Page

### ISSUE THREAD

**Issue by Amber-K** [osu-cascades/neap#9]
Create a simple page where the user will land after signing in. It should show their user information and have a button to start or continue the application. (This button does not necessarily go anywhere yet. Maybe it can go to the static prototype just for fun.)

**Comment by MWidlerSchool** [comment]
My understanding of a landing page is different from this; it's where the user lands when they first arrive. I put the sign in here, and it links forwards to the beginning of the form.

**Comment by MWidlerSchool** [comment]
Completed
