### ISSUE TITLE
Sign In: Returning user should not be taken to the "before you begin" screen

### ISSUE THREAD

**Issue by ybakos** [osu-cascades/neap#94]
As a returning user
when I sign in
I should see ______

But instead I see the "before you begin screen".

**Comment by ybakos** [comment]
New user
Returning user
Annually returning user

**Comment by MWidlerSchool** [comment]
To document our discussion, returning users are either a) finishing an application they started, or b) filling out a new application a year after the last time they did so. Category A should go straight to the application, category B needs to see the before you begin (it may have changed; NI expects it to change every two years).

By Yong's taxonomy, New and Annually Returning Users should see it, Returning Users should not.

**Comment by MWidlerSchool** [comment]
Completed
